name: Lidgren.Network/main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LIDGREN_VERSION: '1.7.4.${{ github.run_number }}'
      ARTIFACT_NAME: 'Lidgren.Network.1.7.4.${{ github.run_number }}'
    outputs:
      artifact_name: '${{ env.ARTIFACT_NAME }}'
      nupkg_base_name: 'AscensionGameDev.Lidgren.Network.${{ env.LIDGREN_VERSION }}'
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - id: build_debug
      name: Build (Debug)
      run: dotnet build --no-restore --configuration Debug -p:VersionPrefix=$LIDGREN_VERSION --version-suffix debug
    - id: build_release
      name: Build (Release)
      run: dotnet build --no-restore --configuration Release -p:VersionPrefix=$LIDGREN_VERSION
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2.2.1
      with:
        name: '${{ env.ARTIFACT_NAME }}'
        path: Lidgren.Network/bin/*/*.*nupkg
        if-no-files-found: error
        retention-days: 1
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Tests (main)
      run: dotnet test --verbosity normal
  publish:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2.0.7
        with:
          name: '${{ needs.build.outputs.artifact_name }}'
      - name: Publish Release
        run: dotnet nuget push 'Release/${{ needs.build.outputs.nupkg_base_name }}.nupkg' --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.LIDGREN_NUGET_API_KEY }}
      - name: Publish Debug
        run: dotnet nuget push 'Debug/${{ needs.build.outputs.nupkg_base_name }}-debug.nupkg' --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.LIDGREN_NUGET_API_KEY }}
